name: Mod publication

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  publish:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - run: chmod +x gradlew
      - name: Publish
        run: ./gradlew publish
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
